### ISSUE TITLE
Does it support sequence diagrams？

### ISSUE THREAD

**Issue by JiangLongLiu** [npgrosser/logseq-diagrams-as-code#1]
Does it support sequence diagrams, such as the list you gave in readme.md ? 
http://blockdiag.com/en/seqdiag/examples.html#simple-diagram
![image](https://user-images.githubusercontent.com/7019907/155290622-9d161d4b-afec-4cae-ac34-3854deba330c.png)

![image](https://user-images.githubusercontent.com/7019907/155290786-4ddccadd-e6c4-4798-9e71-32e87f0c4f59.png)

**Comment by npgrosser** [comment]
Yes, you actually have multiple choices for sequence diagrams:

- https://mermaid-js.github.io/mermaid/#/sequenceDiagram
- http://blockdiag.com/en/seqdiag/index.html
- https://plantuml.com/sequence-diagram
