### ISSUE TITLE
Can't change the style

### ISSUE THREAD

**Issue by 8088boy** [npgrosser/logseq-diagrams-as-code#10]
Hi buddy,
Thanks for your amazing plugin, I like it very much, but only have a little problem.
I followed the instruction and added the following code into file `custom.css` , but nothing happened.
```
.dac-container {
  background-color: #eeeeee;
}
```
Thanks.

**Comment by npgrosser** [comment]
Hey,
thanks for your kind feedback.

My suspicion is that the diagram itself has an opaque background.
So, your gray background is covered by that.

The solution would then depend on the diagram type.

E.g., for Plantuml you can set the `skinparam backgroundcolor` to `transparent`:


Example:

```
@startuml
skinparam backgroundcolor transparent
class Car

Driver - Car : drives >
Car *- Wheel : has 4 >
Car -- Person : < owns

@enduml
```

Most diagram types should have a similar option

**Comment by 8088boy** [comment]
Your suggestion works. Thanks. Here's my code. Is that possible to set the background globally ?

```
@startuml
@startmindmap
skinparam backgroundcolor grey

+ Dimensionality Reduction
++ Feature Selection
+++ Missing Value Ratio
+++ Low Variance Filter
+++ High Correlation Filter
+++ Random Forest
+++ Backward Feature Extraction
+++ Forward Feature Selection
++ Dimensionality Reduction
+++ Components/Factors Based
++++ Factor Analysis
++++ PCA
++++ ICA
+++ Projection Based
++++ ISOMAP
++++ t-SNE
++++ UMAP
@endmindmap
@enduml
```

**Comment by npgrosser** [comment]
There is no option to set diagram-type specific parameters globally.
However, you can of cause just use `skinparam backgroundcolor transparent` on all diagrams to
use the _.dac-container background-color_, as you originally planned.

**Comment by 8088boy** [comment]
The original case is not working. But the inline setting works.
