### ISSUE TITLE
D2 lang support

### ISSUE THREAD

**Issue by avelino** [npgrosser/logseq-diagrams-as-code#12]
Ex: https://play.d2lang.com/?script=pJFRyoNADITfc4q5wO8B9uG_ikR3KaGu2k1sEfHuJerS10IfEybMl5l-Ulty0oCNgAM6QB9Da9wNiQCJATIatk_sAXORzGVt72nd_Uw8oKR6SAnIrk2ljgOrtcscvd8Ak5zUOM-0E13K3_zz9BQ_syLjjYDXUeQX7vX75sLA339l10YiEfumo3ji9T4x7ec6NkzvAAAA__8%3D&sketch=1&theme=5&layout=dagre

**Comment by npgrosser** [comment]
Thanks for the suggestion. 

Fortunately, the Kroki team is currently working on [integrating d2 into the Kroki API](https://github.com/yuzutech/kroki/issues/1323). Since Kroki is already used by logseq-diagrams-as-code for many diagram types, I will wait for Kroki's support instead of implementing my own solution.

**Comment by npgrosser** [comment]
The latest release (0.0.18) now supports D2 Diagrams

**Comment by bjeanes** [comment]
This is working for me but, unlike the other diagrams, the image is teeny tiny
<img width="522" alt="Screenshot 2023-03-25 at 4 42 21 pm" src="https://user-images.githubusercontent.com/2560/227698774-fb0726de-2ea7-4ce7-bb5c-3fece1791073.png">

**Comment by DarkWolf7** [comment]
This should definitely be a bug instead of adding to a previously closed issue for a feature request, but I digress...

I  was using D2 not too long ago and it was working fine - this is definitely new behavior and even diagrams I created when it was working are affected.

**Comment by bjeanes** [comment]
> This should definitely be a bug instead of adding to a previously closed issue for a feature request, but I digress...

Yep you're right. My bad. We can break it out to another issue if the maintainers prefer.

> this is definitely new behavior and even diagrams I created when it was working are affected.

Perhaps the d2lang API changed and whatever is instructing the size is being ignored. I haven't looked at the implementation but I'm pretty sure from what I know about D2 that this is using an external service to generate the image.

**Comment by npgrosser** [comment]
You are right, I will create a separate ticket for this issue as it is not D2 specific. 
Diagram scaling needs some general improvements.
Another (probably) related problem is https://github.com/npgrosser/logseq-diagrams-as-code/issues/6.
I am currently on vacation, but will check it out when I get back.
