### ISSUE TITLE
TikZ

### ISSUE THREAD

**Issue by alxlg** [npgrosser/logseq-diagrams-as-code#13]
Would you mind adding TikZ support like in this Obsidian plugin? https://github.com/artisticat1/obsidian-tikzjax

**Comment by TheMathGuyd** [comment]
PGF/TikZ and Asymptote would be a dream

**Comment by npgrosser** [comment]
There is a PR for kroki to support PGF/TikZ that I will keep an eye on: https://github.com/yuzutech/kroki/pull/1440

**Comment by NickHu** [comment]
> There is a PR for kroki to support PGF/TikZ that I will keep an eye on: [yuzutech/kroki#1440](https://github.com/yuzutech/kroki/pull/1440)

Merged yesterday

**Comment by npgrosser** [comment]
Thanks for the info.
I will release a new plugin version with Tikz support, as soon as the Kroki PR also has been released and deployed. (The latest Kroki release does not include the new feature yet)

**Comment by npgrosser** [comment]
Now that the latest Korki release, [v0.21.0](https://github.com/yuzutech/kroki/releases/tag/v0.21.0), includes PGF/Tikz support, I've released a new version of the plugin to leverage this.
