### ISSUE TITLE
How to submit diagram options to Kroki (eg. graphviz layout)?

### ISSUE THREAD

**Issue by rvrsdl** [npgrosser/logseq-diagrams-as-code#15]
Hi,
Thanks for the great plugin. Is there a way to submit diagram options to the Kroki rendering engine? For example, I would like to use a different layout engine for Graphviz (neato rather than the default dot). It looks like Kroki supports this (https://docs.kroki.io/kroki/setup/diagram-options/#_graphviz) but I'm not sure how to set that option from Logseq. Would it be inside the {{}} ? I've tried doing `{{renderer code_diagram,graphviz, layout="neato"}}` but this doesn't work.
Thanks for your help.

**Comment by npgrosser** [comment]
The latest release (0.0.18) now supports kroki diagram options.
E.g. to specify the graphviz layout engine you would use the key "kroki.diagram.layout":

For example: `{{renderer code_diagram,graphviz,kroki.diagram.layout=neato}}`
