### ISSUE TITLE
Kroki request blocked by CORS policy

### ISSUE THREAD

**Issue by npgrosser** [npgrosser/logseq-diagrams-as-code#16]
There is suddenly an issue with accessing the kroki API (which is used for most diagram types).

`Access to fetch at 'https://kroki.io/d2/svg/eNqrUNC1U6i0UshIzcnJVyjPL8pJ4QIAP2UGXQ==' from origin 'lsp://logseq.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

_Tested with logseq 0.8.16 on Windows 11 and MacOS 13.1_

This only happens with the marketplace version of the plugin.
When installing the local build (using 'Load unpacked plugin') everything works as expected.

**Comment by npgrosser** [comment]
There was a new Kroki release yesterday that might be related. I will check it when I have time

**Comment by npgrosser** [comment]
quickfix/workaround:
https://github.com/npgrosser/logseq-diagrams-as-code/commit/0bafd20bffc1f2f4533c12309494944eeee7b6d4

**Comment by joelash** [comment]
Any update on this? I'm seeing `500`s and `504`s now

**Comment by npgrosser** [comment]
Do you still have this problem? 500 errors indicate that there was a problem with the kroki service itself. 
It works for me, so the issues have probably been resolved

**Comment by joelash** [comment]
I figured it was something related to Kroki, but could also be malformed request; which is also unrelated to CORS.

I'm still getting errors. Strangely it looks like it might just be mermaid based diagrams.

**Comment by npgrosser** [comment]
If you think that this has something to do with the plugin, feel free to post the error message and a diagram example to reproduce the error.

**Comment by tcz717** [comment]
Still seeing it in 0.0.19 

> Access to fetch at 'https://kroki.io/mermaid/svg/eNpLL0osyFAIcbHmctTVtXOCUM7WXE5ACijoDKYAstUIjg==' from origin 'lsp://logseq.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

> CORS error - falling back to default ImgSrcRenderer: TypeError: Failed to fetch

> Failed to load resource: the server responded with a status of 504 ()

**Comment by npgrosser** [comment]
For me the CORS issue seems to be resolved. Which version of logseq do you use @tcz717 ?

**Comment by tcz717** [comment]
> For me the CORS issue seems to be resolved. Which version of logseq do you use @tcz717 ?

My logseq version is 0.8.17

**Comment by npgrosser** [comment]
```
CORS error - falling back to default ImgSrcRenderer: TypeError: Failed to fetch

Failed to load resource: the server responded with a status of 504 ()
```

The "CORS error" part in this error message is a bit misleading. I will update that.
The actual interesting part is "the server responded with a status of 504 ()".

This also seems to be a temporary issue with the Kroki service itself.

**Comment by npgrosser** [comment]
Closing this issue, since the actual CORS problem seems to be resolved.

As it looks, the other issues reported here are not related to this.
Instead, the error log _incorrectly_ indicated "CORS" problems for any Kroki-related exceptions.

This has been updated with https://github.com/npgrosser/logseq-diagrams-as-code/commit/c29b1568882083dd634d8b0841fce7880d6c9084

**Comment by npgrosser** [comment]
Closing this issue, since the actual CORS problem seems to be resolved.

As it looks, the other issues reported here are not related to this.
Instead, the error log _incorrectly_ indicated "CORS" problems for any Kroki-related exceptions.

This has been updated with https://github.com/npgrosser/logseq-diagrams-as-code/commit/c29b1568882083dd634d8b0841fce7880d6c9084
