### ISSUE TITLE
Plugin does not render code 😢

### ISSUE THREAD

**Issue by pat-githubber** [npgrosser/logseq-diagrams-as-code#18]
Hello,

I would like to make use of this amazing plugin but the graph does not render 😢

1. Deactivated all plugins
2. Restart Logseq
3. Installed Diagrams-as-code
4. Restart Logseq
5. Used the shortcut /Create... and pick one type
6. Example code is inserted but now graph visible 

https://user-images.githubusercontent.com/87087327/226100794-bbe0a7a1-1c87-4ccc-8d02-075489134212.mov

Macbook M1 13.2.1 (22D68)
Logseq Version 0.8.18 (0.8.18)
Diagrams as Code 0.0.20

**Comment by pat-githubber** [comment]
Now, I received these errors below.

I do not know but it might be linked to this issue #16 


![image](https://user-images.githubusercontent.com/87087327/226101151-eec13706-82a3-47cd-9f94-4310615d3054.png)

**Comment by npgrosser** [comment]
Can you check if this was a temporary issue?
Does it work now, if you try again?
If not, could you check if there is an error in the [developer console](https://discuss.logseq.com/t/how-to-enable-the-inspector-developer-tools/9428/2)?

**Comment by pat-githubber** [comment]
It works again 🙏 Thank you for commenting
Many thanks for this cool plugin 🚀🙏

**Comment by nocibambi** [comment]
I'm having the same issue.
