### ISSUE TITLE
Does not render on iOS app

### ISSUE THREAD

**Issue by nickjstevens** [npgrosser/logseq-diagrams-as-code#2]
The plugin does not render diagrams on the mobile iOS app (which is currently in beta testing). Screenshot below:

![image](https://user-images.githubusercontent.com/20096844/158021232-7bf9a6c9-8f1c-4b90-a833-c3a2f1df1f89.jpeg)

**Comment by npgrosser** [comment]
Unfortunately, the mobile versions of Logseq do not yet support plugins.
