### ISSUE TITLE
d2's svg preview is very small

### ISSUE THREAD

**Issue by daxartio** [npgrosser/logseq-diagrams-as-code#20]
Maybe you need to set of size to svg object?
![image](https://github.com/npgrosser/logseq-diagrams-as-code/assets/11211587/18c30182-1d65-46cc-a777-75e42fcad267)

**Comment by npgrosser** [comment]
Currently, if the default scaling does not work for you, you need to set it explicitly.
Therefore, you need to click inside the block that contains the rendered diagram.

Then you can change the value `{{renderer code_diagram,d2}}` to `{{renderer code_diagram,d2,containerStyle=width: 200px}}` to set the width to 200px (or whatever width you prefer)

1. Click
![image](https://github.com/npgrosser/logseq-diagrams-as-code/assets/16430605/3536456d-a742-4d42-8bf9-0d5db7824533)
2. Set Width
![image](https://github.com/npgrosser/logseq-diagrams-as-code/assets/16430605/ce5f6fe8-e55c-46ba-91a1-5060551bd0f5)
3. Profit
![image](https://github.com/npgrosser/logseq-diagrams-as-code/assets/16430605/a02cbe9a-76f4-4ebd-a07e-d77329abc672)

**Comment by daxartio** [comment]
Thank you for your answering!

I forgot to look at issues the answer already had been created.
