### ISSUE TITLE
Arrow sizes inconsistent on flow charts

### ISSUE THREAD

**Issue by pagiraud** [npgrosser/logseq-diagrams-as-code#23]
Hi,
Please consider this minimal flow chart: 

```
graph TD;
A<-->B;
```
As you can see if you enter it in Logseq, the opening arrow (A side) is much bigger than the ending one (B side). In fact, ending arrows are so small that they are very difficult to spot.

Would you consider making all arrows the size of the opening ones?

Thanks in advance,

**Comment by npgrosser** [comment]
This seems to be an issue with Mermaid or [Kroki](https://github.com/yuzutech/kroki) and unfortunately out of my control.
See here https://[kroki.io/mermaid/svg/eNpLL0osyFAIcbHmcrTR1bVzsgYAL4MEog==](https://kroki.io/mermaid/svg/eNpLL0osyFAIcbHmcrTR1bVzsgYAL4MEog==)

The issue can also be reproduced on https://kroki.io/
