### ISSUE TITLE
D2 theme and sketch settings?

### ISSUE THREAD

**Issue by hwang63130** [npgrosser/logseq-diagrams-as-code#24]
The original D2Lang has CLI options to set diagram theme and sketch options, and Kroki supports both options as URL parameters. For example:
https://[kroki.io/d2/svg/eNqrUNC1U6gEAAWdAZ0=?theme=1&sketch=1](https://kroki.io/d2/svg/eNqrUNC1U6gEAAWdAZ0=?theme=1&sketch=1)

I'm wondering if it is possible to have these two features turned on in logseq-diagrams-as-code?

**Comment by npgrosser** [comment]
Yes this is possible (but currently undocumented)
See https://github.com/npgrosser/logseq-diagrams-as-code/issues/15

For you example, this is how the render block content would look like `{{renderer code_diagram,d2, kroki.diagram.theme=1&kroki.diagram.sketch=1}}`

**Comment by npgrosser** [comment]
https://github.com/npgrosser/logseq-diagrams-as-code/commit/6e2d0337300e3257b9a2e640b55f0c180664c9d1
