### ISSUE TITLE
How to edit code inside {{}} ?

### ISSUE THREAD

**Issue by notuntoward** [npgrosser/logseq-diagrams-as-code#5]
After I've created a diagram, how do I edit the diagram metacode inside of the `{{}}`, for example, to add a title?  Once I see a rendered image of the diagram, nothing happens when I click on the block text.  I don't know what I should see, but I was expecting the raw markup, like I see in other blocks.  Then, in the markup, I thought I'd see the `{{}}` stuff shown in the README.

If I expand the block, so I see the diagram code -- in my case, the mermaid code --  I still don't see any place to edit `{{}}`

**Comment by npgrosser** [comment]
If you click on the right side next to the rendered diagram, the metacode should become editable.

**Comment by notuntoward** [comment]
Huh, when I click there, nothing happens.  I tried left, right and middle clicks.  This is on Windows.  Maybe you on MacOS or something?

**Comment by npgrosser** [comment]
hey, sorry for the late response.

Actually, this should also work on windows.
Alternatively, you can select a sibling block (directly above or below your diagram) and use the arrow keys to move the cursor to the 'diagram block'. The metacode should then be editable
