### ISSUE TITLE
Asciimath colors do not work well for dark theme

### ISSUE THREAD

**Issue by mdallaire** [npgrosser/logseq-diagrams-as-code#9]
Asciimath formula are hard to read using the logseq default dark theme (and other dark themes).

![image](https://user-images.githubusercontent.com/23340663/189497063-daf51dc3-8b9a-4f85-a6f8-98a502a16108.png)

**Comment by npgrosser** [comment]
The simplest solution would be to change the background color for Asciimath.
To do this, you can add a _dac-container-asciimath_ class to your custom.css file (Settings/General/Edit custom.css)

For example:
```
.dac-container-asciimath {
  background: #084755;
  padding: 3px;
}
```

_(See 'Decorating Diagrams' in README.md)_

**Comment by mdallaire** [comment]
Thank you for this!
I ended up using `#93a1a1`. The fit is good with the dark theme and provides good readability too.
![image](https://user-images.githubusercontent.com/23340663/189916093-6338fa9e-2111-4439-a1a1-5eb04f83f8fd.png)
